server:
  port: 9008
spring:
  application:
    name: sample-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.30.132:3306/sample_user?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.30.132
jwt:
  config:
    key: itcast
    ttl: 360000